name: Get npm token
description: Get npm token for the specified repository
inputs:
  target_dir:
    description: Name of target directory
    required: true
runs:
  using: "composite"
  steps:
    - id: package_json
      run: echo "::set-output name=content::$(cat ./package.json | tr -d '\n')"
      working-directory: ${{ inputs.target_dir }}
      shell: bash
    - id: npm_token
      run: |
        set +x
        if [[ ${{ fromJson(steps.package_json.outputs.content).name }} =~ @akashic-extension/.+ ]]; then
          echo "::set-output name=value::$EXTENSION_NPM_TOKEN"
        else
          echo "::set-output name=value::$NPM_TOKEN"
        fi
        set -x
      shell: bash
outputs:
  token:
    description: "Npm token for the specified repository"
    value: ${{ steps.npm_token.outputs.value }}
