name: Sample

# 新しいコミットがリポジトリにプッシュされるたびにこのワークフローを実行する
on:
  push:
    branches:
      - master

jobs:
  # ジョブキーを設定する。 ジョブ名が指定されていない場合、
  # キーはジョブ名として表示される
  sample1:
    # ジョブ名を付ける
    name: Run Sample (Echo)
    # 実行するマシンのタイプを設定する
    runs-on: ubuntu-latest

    steps:
      # ubuntu-latest マシンでリポジトリのコピーをチェックアウトする
      - name: Checkout code
        uses: actions/checkout@v2

      # Super-Linter アクションを実行する
      - name: Echo Only
        run: |
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
