name: Publish And Release

on:
  workflow_dispatch:
    inputs:
      git_repository:
        description: Git repository
        required: true
      target_branch:
        description: Target branch
        required: true
        default: master
      target_tag:
        description: Target tag
        required: true
        default: latest

env:
  NODE_VERSION: 12

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          path: workflows
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: dera-/${{ github.event.inputs.git_repository }}
          ref: ${{ github.event.inputs.target_branch }}
          path: target
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
        working-directory: workflows
      - run: npm install
        working-directory: target
      - run: npm test
        working-directory: target
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./target/package.json
          tag: ${{ github.event.inputs.target_tag }}
          access: public
      - name: Generate release note
        id: release_note
        uses: ./workflows/generateReleaseNote
        with:
          repository_path: ${{ github.workspace }}/target
      - name: Create release note
        uses: actions/create-release@master
        env:
          # 他リポジトリに対して操作を行う場合secret.GITHUB_TOKENとは別にgithubトークンを利用する必要があるためsecret.GH_TOKENを用意
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: ${{ steps.release_note.outputs.version }}
          release_name: Release ${{ steps.release_note.outputs.version }}
          body: ${{ steps.release_note.outputs.body }}
          draft: false
          prerelease: false
          commitish: ${{ github.event.inputs.target_branch }}
          owner: dera-
          repo: ${{ github.event.inputs.git_repository }}
