name: Release For Monorepo

on:
  workflow_dispatch:
    inputs:
      git_repository:
        description: Git repository of monorepo using lerna
        required: true
      next_version:
        description: 通常時は patch, minor, major, prelease のどれかを指定します。更新対象が無くても publish したい場合は force-patch-all を、Github 上の package.json に記載されているバージョンのまま publish したい場合は from-package を指定します。
        required: true
      target_branch:
        description: Target branch
        required: true
        default: master
      publish_dist_tag:
        description: Target tag
        required: true
        default: latest

env:
  NODE_VERSION: 12
  GIT_USER_NAME: dera-
  GIT_USER_EMAIL: alchemy.and.fairy@gmail.com

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          path: workflows
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: akashic-games/${{ env.GIT_REPOSITORY }}
          ref: ${{ env.TARGET_BRANCH }}
          path: target
          token: ${{ env.GH_TOKEN }}
        env:
          GIT_REPOSITORY: ${{ github.event.inputs.git_repository }}
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # env.GITHUB_TOKENは既に存在するため、別の変数名にする
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org
      - run: npm install
        working-directory: workflows
      - run: npm ci
        working-directory: target
      - name: Choose npm token
        id: npm_token
        uses: ./workflows/chooseNpmToken
        with:
          target_dir: target
          npm_token_for_akashic: ${{ secrets.NPM_TOKEN }}
          npm_token_for_akashic_extension: ${{ secrets.EXTENSION_NPM_TOKEN }}
      - name: Set git user infomartion
        run: |
          git config user.name $GIT_USER_NAME
          git config user.email $GIT_USER_EMAIL
        working-directory: target
      # - name: Setup node to publish target
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     registry-url: https://registry.npmjs.org
      - name: Publish
        run: |
          if [[ ${{ github.event.inputs.next_version }} = "from-package" ]]; then
            ./node_modules/.bin/lerna publish from-package --yes
          else
            npm run publish:${{ github.event.inputs.next_version }}
          fi
        env:
          GITHUB_AUTH: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ steps.npm_token.outputs.token }}
        working-directory: target
