name: Release For Monorepo

on:
  workflow_dispatch:
    inputs:
      git_repository:
        description: Git repository of monorepo using lerna
        required: true
      next_version:
        description: 通常時は patch, minor, major, prelease のどれかを指定します。更新対象が無くても publish したい場合は force-patch-all を、Github 上の package.json に記載されているバージョンのまま publish したい場合は from-package を指定します。
        required: true
      target_branch:
        description: Target branch
        required: true
        default: master
      publish_dist_tag:
        description: Target tag
        required: true
        default: latest

env:
  NODE_VERSION: 12
  GIT_USER_NAME: dera-
  GIT_USER_EMAIL: alchemy.and.fairy@gmail.com

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          path: workflows
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: dera-/${{ github.event.inputs.git_repository }}
          ref: ${{ github.event.inputs.target_branch }}
          path: target
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
        working-directory: workflows
      - name: Install node modules
        run: npm install --no-package-lock
        working-directory: target
      - name: Get npm token
        id: npm_token
        uses: ./workflows/getNpmToken
        with:
          repository_path: ${{ github.workspace }}/target
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          EXTENSION_NPM_TOKEN: ${{ secrets.EXTENSION_NPM_TOKEN }}
      # - name: Install ssh key
      #   uses: shimataro/ssh-key-action@v1
      #   with:
      #     private-key: ${{ secrets.REPOSITORY_DEPLOY_KEY }}
      - name: Publish
        run: |
          git config user.name ${{ env.GIT_USER_NAME }}
          git config user.email ${{ env.GIT_USER_EMAIL }}
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          if [[ ${{ github.event.inputs.next_version }} = "from-package" ]]; then
            ./node_modules/.bin/lerna publish from-package --yes
          else
            npm run publish:${{ github.event.inputs.next_version }}
          fi
        env:
          NPM_TOKEN: ${{ steps.npm_token.outputs.token }}
          GITHUB_AUTH: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        working-directory: target
