name: Publish And Release

on:
  workflow_dispatch:
    inputs:
      git_repository:
        description: Git Repository
        required: true
      target_branch:
        description: Target Branch
        required: true
        default: master
      target_tag:
        description: Target Tag
        required: true
        default: latest

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v2
        with:
          path: workflows
      - name: Checkout Target Repository
        uses: actions/checkout@v2
        with:
          repository: dera-/${{ github.event.inputs.git_repository }}
          ref: ${{ github.event.inputs.target_branch }}
          path: target
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          # TODO: envにする
          node-version: 12
      - run: |
        cd workflows
        npm install
      # - name: Publish
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     package: ./target/package.json
      #     tag: ${{ github.event.inputs.target_tag }}
      #     access: public
      # - name: Get Release Note
      #   id: releaseNote
      #   uses: ./workflows/generateReleaseNote
      # - name: Create Release Note
        # uses: actions/create-release@master
        # env:
        #   # 他リポジトリに対して操作を行う場合secret.GITHUB_TOKENとは別にgithubトークンを利用する必要があるためsecret.GH_TOKENを用意
        #   GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        # with:
        #   tag_name: ${{ steps.releaseNote.outputs.version }}
        #   release_name: Release ${{ steps.releaseNote.outputs.version }}
        #   body: ${{ steps.releaseNote.outputs.body }}
        #   draft: false
        #   prerelease: false
        #   commitish: ${{ github.event.inputs.target_branch }}
        #   owner: dera-
        #   repo: ${{ github.event.inputs.git_repository }}