name: Publish And Release

on:
  workflow_dispatch:
    inputs:
      git_repository:
        description: 'Git Repository'
        required: true
      target_branch:
        description: 'Target Branch'
        required: true
        default: 'master'
      target_tag:
        description: 'Target Tag'
        required: true
        default: 'latest'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v2
      - name: Checkout Target Repository
        uses: actions/checkout@v2
        with:
          repository: dera-/${{ github.event.inputs.git_repository }}
          ref: ${{ github.event.inputs.target_branch }}
          path: target
      # - name: Check File
      #   run: |
      #     pwd
      #     ls -la
      #     find / -name action.yml
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Npm Install
        run: npm install
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./target/package.json"
          tag: ${{ github.event.inputs.target_tag }}
          access: "public"
      - name: Get Release Note
        id: releaseNote
        uses: ./getReleaseNote
      - name: Check Output
          run: |
            echo "${{ steps.releaseNote.outputs.version }}"
            echo "{{ steps.releaseNote.outputs.body }}"
      - name: Create Release Note
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: "v${{ steps.releaseNote.outputs.version }}"
          release_name: "Release v${{ steps.releaseNote.outputs.version }}"
          body: ${{ steps.releaseNote.outputs.body }}
          draft: false
          prerelease: false
          owner: dera-
          repo: ${{ github.event.inputs.git_repository }}
